### PR TITLE
Fix `Arbitrary` derivation for variants with size increasing by one

### LINKED ISSUE #141: Struct enum variant with only one field as first variant breaks Arbitrary derive.
Struct enum variant with only one field as first variant breaks Arbitrary derive. 
(`let (param_0, param_1) = param_1;` was not put in for the second variant.)

this breaks test:
```
diff --git a/proptest-derive/tests/enum.rs b/proptest-derive/tests/enum.rs
index 3ddcc70..e3a5507 100644
--- a/proptest-derive/tests/enum.rs
+++ b/proptest-derive/tests/enum.rs
@@ -162,6 +162,12 @@ enum SameType {
     B(usize),
 }
 
+#[derive(Clone, Debug, Arbitrary)]
+enum Beca {
+    A{u: u64},
+    B{u: u64, i: i32},
+}
+
 
 #[test]
 fn asserting_arbitrary() {
@@ -194,4 +200,6 @@ fn asserting_arbitrary() {
     assert_arbitrary::<T25>();
     assert_arbitrary::<Alan>();
     assert_arbitrary::<SameType>();
+
+    assert_arbitrary::<Beca>();
 }

```

### LINKED ISSUE #146: Arbitrary not being derived on Enums correctly
# The problem

I think I've found a bug in `proptest_derive` for enums.  The following code:

```rust
use proptest_derive::Arbitrary;

#[derive(Debug, Arbitrary)]
pub enum SampleEnum {
    Empty,
    One(u8),
    Two(u8, u16)
}

fn main() {
    println!("Hello, world!");
}
```

Yields the following error:

```
error[E0308]: mismatched types
 --> src/main.rs:3:17
  |
3 | #[derive(Debug, Arbitrary)]
  |                 ^^^^^^^^^ expected (), found tuple
  |
  = note: expected type `()`
             found type `((), ())`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `proptest_enum_issue`.

To learn more, run the command again with --verbose.
cfkaran2@EMANE:~/Desktop/bug_reports/proptest_enum_issue$
```
Commenting out some of the lines will make it work, but it seems to be arbitrary as to which lines.

# Meta

```
cfkaran2@EMANE:~/Desktop/bug_reports/proptest_enum_issue$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

cfkaran2@EMANE:~/Desktop/bug_reports/proptest_enum_issue$ uname -a
Linux EMANE 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cfkaran2@EMANE:~/Desktop/bug_reports/proptest_enum_issue$ rustc -Vv
rustc 1.34.2 (6c2484dc3 2019-05-13)
binary: rustc
commit-hash: 6c2484dc3c532c052f159264e970278d8b77cdc9
commit-date: 2019-05-13
host: x86_64-unknown-linux-gnu
release: 1.34.2
LLVM version: 8.0

cfkaran2@EMANE:~/Desktop/bug_reports/proptest_enum_issue$ cargo -Vv
cargo 1.34.0 (6789d8a0a 2019-04-01)
release: 1.34.0
commit-hash: 6789d8a0a54a96d95365c4e1fb01d47a5eed9937
commit-date: 2019-04-01
```

### PR DESCRIPTION
**Pull request by jakubadamw**
Fixes #141.
Fixes #146.

### CODE REVIEW

File: proptest-derive/src/derive.rs [hunk 1]
```diff
@@ -540,11 +540,7 @@ fn variant_no_explicit_strategy<C>(
             ctor
         } else {
             let pref = acc.add_param(params_ty);
-            if pref + 1 == count {
-                ctor
-            } else {
-                extract_all(ctor, count, FromReg::Num(pref))
-            }
+            extract_all(ctor, count, FromReg::Num(pref))
```
Comment (Centril) [inline proptest-derive/src/derive.rs]: I don't exactly recall why this `if` expression was there (Note to self: leave comments damn it!), but it seems to work since you have tests. =P

Comment (jakubadamw) [reply proptest-derive/src/derive.rs]: @Centril, indeed, I was trying to grasp it myself. When I added introspection into the first branch of the `if`, it was being hit only in the tests that I've just added. I suppose it was originally meant to be an optimization of some sort but that's all I could figure. :)
